In [1]:
import numpy as np

In [2]:
def loadEdges(filename):
    edges_list = []
    edges_file = open(filename,'r')
    for line in edges_file:
        if(line != "EOF"):
            temp_line = line.replace("\n","")
            begin,end,cost = temp_line.split(" ")
            edges_list.append([int(begin),int(end),int(cost)])
    return np.array(edges_list)

In [152]:
class Graph(): 
  
    def __init__(self, num_nodes): 
        self.num_nodes = num_nodes
        self.adjacency_matrix = np.ones([num_nodes, num_nodes])*-1
        
    def fillGraph(self,edges):
        for i in range(self.num_nodes):
            edges_for_i_node = np.where(edges[:,0]==i+1)[0]
            if(len(edges_for_i_node)>0):
                for edge in edges_for_i_node:
                    self.adjacency_matrix[i,edges[edge][1]-1] = edges[edge,2]
            self.adjacency_matrix[i,i] = 0
            
    def dijkstra(self,source_node):
        # Se guardan los costos asigndos desde un nodo fuente en un numpy array de dimensión Nx1
        costs = self.adjacency_matrix[source_node]
        costs[costs == -1] = np.inf
        costs = costs.reshape((self.num_nodes,1))
        index_to_cost = np.arange(self.num_nodes, dtype=int).reshape((self.num_nodes,1))
        index_from_source = np.full((self.num_nodes,1),source_node, dtype=int)
        index_from_source = np.append(index_to_cost,index_from_source,axis=1)
        costs = np.append(index_from_source,costs,axis=1)
        # Se guarda el nodo con distancia 0, es decir, el nodo inicial en un numpy array de soluciones
        # luego es eliminado del array de costos
        dijkstra = [costs[source_node]]
        costs = np.delete(costs,source_node,axis =0)
        while(len(costs)>0):
            min_node_index = np.argmin(costs[:,2])
            current_node = costs[min_node_index]
            if(np.min(current_node[2]) == np.inf):
                break
            dijkstra = np.append(dijkstra,[costs[min_node_index]],axis =0)
            costs = np.delete(costs,min_node_index,axis =0)
            for i in range(len(costs)):
                int_x = int(current_node[0])
                int_y = int(costs[i][0])
                current_node_to_i_cost = self.adjacency_matrix[int_x,int_y]
                if(current_node_to_i_cost != -1 and current_node_to_i_cost !=0):
                    temp_cost = current_node_to_i_cost + current_node[2]
                    if(temp_cost < costs[i,2]):
                        costs[i,1] =  current_node[0]
                        costs[i,2] = temp_cost
        return dijkstra
    
    def dialDijkstra(self,source_node,w):
        
        
            
            
                
                    

In [153]:
nodes_file = open('nodos.txt','r')
number_nodes = int(nodes_file.readlines()[0])
edges = loadEdges('arcos.txt')

In [154]:
g = Graph(number_nodes)
g.fillGraph(edges)

In [155]:
g.adjacency_matrix

array([[ 0.,  2.,  4., -1., -1., -1.],
       [-1.,  0.,  1.,  4.,  2., -1.],
       [-1., -1.,  0., -1.,  3., -1.],
       [-1., -1., -1.,  0., -1.,  2.],
       [-1., -1., -1.,  3.,  0.,  2.],
       [-1., -1., -1., -1., -1.,  0.]])

In [161]:
g.dijkstra(1)

array([[1., 1., 0.],
       [2., 1., 1.],
       [4., 1., 2.],
       [3., 1., 4.],
       [5., 4., 4.]])

In [150]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
edges

In [ ]:
np.min([345,87])

In [ ]:
asd1 = np.full((6,1),5)
asd1.shape

In [ ]:
asd2 = g.adjacency_matrix[0].reshape((6,1))
asd2.shape

In [ ]:
np.append(asd1,asd2,axis=1)

In [ ]:
costs_a = np.array([[0,1,2],[0,4,5]])

In [ ]:
costs_a[1,2]